minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@shun-shobon/style-guide"

allowBuilds:
  "@tailwindcss/oxide": true
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true

publicHoistPattern:
  - "*eslint*"

saveExact: true

strictDepBuilds: true

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 10080
